ItemNames: ; 472d (1:472d)
	db "MASTER BALL@"
	db "HYPER BALL@"
	db "SUPER BALL@"
	db "POKé BALL@"
	db "CARTE@"
	db "BICYCLETTE@"
	db "?????@"
	db "SAFARI BALL@"
	db "POKéDEX@"
	db "PIERRE LUNE@"
	db "ANTIDOTE@"
	db "ANTI-BRULE@"
	db "ANTIGEL@"
	db "REVEIL@"
	db "ANTI-PARA@"
	db "GUERISON@"
	db "POTION MAX@"
	db "HYPER POTION@"
	db "SUPER POTION@"
	db "POTION@"
	db "BADGE ROCHE@"
	db "BADGECASCADE@"
	db "BADGE FOUDRE@"
	db "BADGE PRISME@"
	db "BADGE AME@"
	db "BADGE MARAIS@"
	db "BADGE VOLCAN@"
	db "BADGE TERRE@"
	db "CORDE SORTIE@"
	db "REPOUSSE@"
	db "VIEIL AMBRE@"
	db "PIERRE FEU@"
	db "PIERREFOUDRE@"
	db "PIERRE EAU@"
	db "PV PLUS@"
	db "PROTEINE@"
	db "FER@"
	db "CARBONE@"
	db "CALCIUM@"
	db "SUPER BONBON@"
	db "FOSSILE DOME@"
	db "NAUTILE@"
	db "CLE SECRETE@"
	db "?????@"
	db "BON COMMANDE@"
	db "PRECISION +@"
	db "PIERREPLANTE@"
	db "CARTE MAGN.@"
	db "PEPITE@"
	db "PP PLUS@"
	db "POKéPOUPEE@"
	db "TOTAL SOIN@"
	db "RAPPEL@"
	db "RAPPEL MAX@"
	db "DEFENSE SPEC@"
	db "SUPEREPOUSSE@"
	db "MAX REPOUSSE@"
	db "MUSCLE +@"
	db "JETONS@"
	db "EAU FRAICHE@"
	db "SODA COOL@"
	db "LIMONADE@"
	db "PASSE BATEAU@"
	db "DENT D'OR@"
	db "ATTAQUE +@"
	db "DEFENSE +@"
	db "VITESSE +@"
	db "SPECIAL +@"
	db "BOITE JETON@"
	db "COLIS CHEN@"
	db "CHERCH'OBJET@"
	db "SCOPE SYLPHE@"
	db "POKéFLUTE@"
	db "CLE ASC.@"
	db "MULTI EXP@"
	db "CANNE@"
	db "SUPER CANNE@"
	db "MEGA CANNE@"
	db "PP PLUS@"
	db "HUILE@"
	db "HUILE MAX@"
	db "ELIXIR@"
	db "MAX ELIXIR@"
	db "2EME SS@"
	db "1ER SS@"
	db "RDC@"
	db "1ER ETAGE@"
	db "2EME ETAGE@"
	db "3EME ETAGE@"
	db "4EME ETAGE@"
	db "5EME ETAGE@"
	db "6EME ETAGE@"
	db "7EME ETAGE@"
	db "8EME ETAGE@"
	db "9EME ETAGE@"
	db "10EME ETAGE@"
	db "4EME SS@"
