MoveNames:: ; b0000 (2c:4000)
	db "ECRAS'FACE@"
	db "POING-KARATE@"
	db "TORGNOLES@"
	db "POING COMETE@"
	db "ULTIMAPOING@"
	db "JACKPOT@"
	db "POING DE FEU@"
	db "POINGLACE@"
	db "POING-ECLAIR@"
	db "GRIFFE@"
	db "FORCE POIGNE@"
	db "GUILLOTINE@"
	db "COUPE-VENT@"
	db "DANSE-LAMES@"
	db "COUPE@"
	db "TORNADE@"
	db "CRU-AILE@"
	db "CYCLONE@"
	db "VOL@"
	db "ETREINTE@"
	db "SOUPLESSE@"
	db "FOUET LIANES@"
	db "ECRASEMENT@"
	db "DOUBLE PIED@"
	db "ULTIMAWASHI@"
	db "PIED SAUTE@"
	db "MAWASHI GERI@"
	db "JET DE SABLE@"
	db "COUP D'BOULE@"
	db "KOUD'KORNE@"
	db "FURIE@"
	db "EMPAL'KORNE@"
	db "CHARGE@"
	db "PLAQUAGE@"
	db "LIGOTAGE@"
	db "BELIER@"
	db "MANIA@"
	db "DAMOCLES@"
	db "MIMI-QUEUE@"
	db "DARD-VENIN@"
	db "DOUBLE-DARD@"
	db "DARD-NUEE@"
	db "GROZ'YEUX@"
	db "MORSURE@"
	db "RUGISSEMENT@"
	db "HURLEMENT@"
	db "BERCEUSE@"
	db "ULTRASON@"
	db "SONICBOOM@"
	db "ENTRAVE@"
	db "ACIDE@"
	db "FLAMMECHE@"
	db "LANCE-FLAMME@"
	db "BRUME@"
	db "PISTOLET A O@"
	db "HYDROCANON@"
	db "SURF@"
	db "LASER GLACE@"
	db "BLIZZARD@"
	db "RAFALE PSY@"
	db "BULLES D'O@"
	db "ONDE BOREALE@"
	db "ULTRALASER@"
	db "PICPIC@"
	db "BEC VRILLE@"
	db "SACRIFICE@"
	db "BALAYAGE@"
	db "RIPOSTE@"
	db "FRAPPE ATLAS@"
	db "FORCE@"
	db "VOL-VIE@"
	db "MEGA-SANGSUE@"
	db "VAMPIGRAINE@"
	db "CROISSANCE@"
	db "TRANCH'HERBE@"
	db "LANCE-SOLEIL@"
	db "POUDRE TOXIK@"
	db "PARA-SPORE@"
	db "POUDRE DODO@"
	db "DANSE-FLEUR@"
	db "SECRETION@"
	db "DRACO-RAGE@"
	db "DANSEFLAMME@"
	db "ECLAIR@"
	db "TONNERRE@"
	db "CAGE-ECLAIR@"
	db "FATAL-FOUDRE@"
	db "JET-PIERRES@"
	db "SEISME@"
	db "ABIME@"
	db "TUNNEL@"
	db "TOXIK@"
	db "CHOC MENTAL@"
	db "PSYKO@"
	db "HYPNOSE@"
	db "YOGA@"
	db "HATE@"
	db "VIVE-ATTAQUE@"
	db "FRENESIE@"
	db "TELEPORT@"
	db "TENEBRES@"
	db "COPIE@"
	db "GRINCEMENT@"
	db "REFLET@"
	db "SOIN@"
	db "ARMURE@"
	db "LILLIPUT@"
	db "BROUILLARD@"
	db "ONDE FOLIE@"
	db "REPLI@"
	db "BOUL'ARMURE@"
	db "BOUCLIER@"
	db "MUR LUMIERE@"
	db "BUEE NOIRE@"
	db "PROTECTION@"
	db "PUISSANCE@"
	db "PATIENCE@"
	db "METRONOME@"
	db "MIMIQUE@"
	db "DESTRUCTION@"
	db "BOMB'OEUF@"
	db "LECHOUILLE@"
	db "PUREDPOIS@"
	db "DETRITUS@"
	db "MASSD'OS@"
	db "DEFLAGRATION@"
	db "CASCADE@"
	db "CLAQUOIR@"
	db "METEORES@"
	db "COUD'KRANE@"
	db "PICANON@"
	db "CONSTRICTION@"
	db "AMNESIE@"
	db "TELEKINESIE@"
	db "E-COQUE@"
	db "PIED VOLTIGE@"
	db "INTIMIDATION@"
	db "DEVOREVE@"
	db "GAZ TOXIK@"
	db "PILONNAGE@"
	db "VAMPIRISME@"
	db "GROBISOU@"
	db "PIQUE@"
	db "MORPHING@"
	db "ECUME@"
	db "UPPERCUT@"
	db "SPORE@"
	db "FLASH@"
	db "VAGUE PSY@"
	db "TREMPETTE@"
	db "ACIDARMURE@"
	db "PINCE-MASSE@"
	db "EXPLOSION@"
	db "COMBO-GRIFFE@"
	db "OSMERANG@"
	db "REPOS@"
	db "EBOULEMENT@"
	db "CROC DE MORT@"
	db "AFFUTAGE@"
	db "ADAPTATION@"
	db "TRIPLATTAQUE@"
	db "CROC FATAL@"
	db "TRANCHE@"
	db "CLONAGE@"
	db "LUTTE@"

