TrainerNames: ; 399ff (e:59ff)
	db "GAMIN@"
	db "SCOUT@"
	db "FILLETTE@"
	db "MARIN@"
	db "DRESSEUR JR♂@"
	db "DRESSEUR JR♀@"
	db "POK",$bc,"MANIAC@"
	db "INTELLO@"
	db "MONTAGNARD@"
	db "MOTARD@"
	db "PILLARD@"
	db "MECANO@"
	db "JONGLEUR@"
	db "PECHEUR@"
	db "NAGEUR@"
	db "LOUBARD@"
	db "CROUPIER@"
	db "CANON@"
	db "KINESISTE@"
	db "ROCKER@"
	db "JONGLEUR@"
	db "DOMPTEUR@"
	db "ORNITHOLOGUE@"
	db "KARATEKA@"
	db "RIVAL1@"
	db "PROF.CHEN@"
	db "CHIEF@"
	db "SCIENTIFIQUE@"
	db "GIOVANNI@"
	db "ROCKET@"
	db "TOPDRESSEUR♂@"
	db "TOPDRESSEUR♀@"
	db "ALDO@"
	db "PIERRE@"
	db "ONDINE@"
	db "MAJOR BOB@"
	db "ERIKA@"
	db "KOGA@"
	db "AUGUSTE@"
	db "MORGANE@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "OLGA@"
	db "EXORCISTE@"
	db "AGATHA@"
	db "PETER@"
